### ISSUE TITLE
[BREAKING] Get rid of .swal2-header and .swal2-content

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2224]
## Current behavior

There are currently opinionated and unnecessary containers in popup markup:

- `.swal2-header`: https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/dom/init.js#L10
- `.swal2-content`: https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/dom/init.js#L17

Because of those containers the ability to place icon/image/close button/input suffers. E.g. it's not possible to achieve #2222 in a nice way without adding`position: absolute` for the icon:

![image](https://user-images.githubusercontent.com/6059356/114709751-a448e400-9d35-11eb-85a0-e24867926da3.png)

### Expected behavior

`.swal2-header` and `.swal2-content` containers should not be present. They do not bring any value and because of them the customisation of popups suffers.

### TODO

- [ ] remove `.swal2-header`
- [ ] remove `.swal2-content`
- [ ] remove `position: absolute` from `swal2-close`
